version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: hlf_database
      MYSQL_USER: hlf_user
      MYSQL_PASSWORD: hlf_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    
  
# Volumes
volumes:
  db-data:
